general.import = []

[window]
padding = { x = 5, y = 5 }
decorations = "None"
startup_mode = "Maximized"
opacity = 0.9

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 11.25
